spring:
  boot:
    zk:
      enable: true
      cluster: 127.0.0.1:2181
      nameSpace: example
      sessionTimeOut: 60000
      connectionTimeOut: 30000
      userName: liuhailin
      password: liuhailin
